name: flip_flop
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  firebase_core: ^0.4.0+9
  firebase_analytics: ^2.1.1+3

  cloud_firestore: ^0.12.9+5
  flutter_svg: 0.14.3
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.1+1 
  eva_icons_flutter: ^1.0.4
  rxdart: ^0.21.0
  provider: 3.1.0
  font_awesome_flutter: 8.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
  # fonts:
  #   - family: Orbitron
  #     fonts:
  #       - asset: fonts/Nunito/Nunito-Regular.ttf
  #       - asset: fonts/Nunito/Nunito-Light.ttf
  #       - asset: fonts/Nunito/Nunito-Bold.ttf
  #         weight: 300

